import Head from 'next/head'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Image  from 'next/image'
import Weather from '../components/Weather'
import Spinner from '../components/Spinner'

export default function Home() {

const [city,setCity]=useState('');
const [weather,setWeather]=useState({});
const [loading,setLoading] = useState(false);
 
const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;
 
  const fetchWeather =(e)=>{
    e.preventDefault(),
    setLoading(true);
    axios.get(url).then((response)=>{
      setWeather(response.data);
      
    });
    setCity('');
    setLoading(false);
  };
  if(loading) {
    return <Spinner/>
     
  }else {
    return (
      <div>
        <Head>
          <title>Weather app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  {/* overlay */}
        <div className='absolute top-0  left-0 right-0 bottom-0 bg-black/70 z-[1]' />
      <Image src='https://images5.alphacoders.com/872/thumb-1920-872688.jpg' 
      layout='fill'
      className='object-top'
      
      />
      {/* Search */}
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto  pt-4 px-4  text-white z-10' >
        <form  onSubmit={fetchWeather} className='flex justify-between items-center w-full  m-auto p-3 bg-black border-white-300 text-white rounded-2xl' >
          <div>
            <input onChange={(e)=>setCity(e.target.value)} className='bg-transparent border-none text-white focus:outline-none  text-2xl  ' type="text" placeholder="Şehir adı giriniz."/>
          </div>
           <button  onClick={fetchWeather}><BsSearch  size={20}/></button>
        </form>
      </div>
      {/* weather */}
  
      {weather.main && <Weather data={weather}/>}
  
      
      </div>
    );

  }
  
}
